export const servicePageConfigs = {
  "graphic-design-services-bangladesh": {
    service: "graphic-design",
    imageSettingKey: "graphic_design_image",
    ignoreCmsTitle: true,
    ignoreCmsContent: true,
    eyebrow: "Graphic Design Services",
    title: <>Graphic Design Services <span className="text-primary">Bangladesh.</span></>,
    schemaTitle: "Graphic Design Services Bangladesh",
    description: "Graphic design services in Bangladesh for logos, brand identity, marketing materials, social media creatives, and ad visuals that make your business look clear and professional.",
    icon: "brush",
    heroImage: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=1200&q=80",
    overviewTitle: "Design Work Built For Brand Clarity",
    overview: "Good design is not just decoration. I create practical graphic design assets for businesses in Dhaka and across Bangladesh that need consistent visuals for branding, campaigns, social media, print, and digital marketing.",
    portfolioTitle: "Featured Graphic Design Projects",
    features: [
      { icon: "draw", title: "Logo & Brand Identity", text: "Memorable logos, color direction, typography, and visual rules that help your business look consistent everywhere." },
      { icon: "campaign", title: "Marketing & Ad Creatives", text: "Flyers, banners, brochures, social posts, and ad visuals designed around offers, audiences, and campaign goals." },
      { icon: "palette", title: "Social Media Design", text: "Branded post templates, carousel designs, and promotional graphics for Facebook, Instagram, and other digital channels." },
    ],
    toolsTitle: "Design Apps I Use",
    toolsDescription: "Professional tools used to create clean, editable, and export-ready graphic design assets.",
    tools: [
      {
        name: "Adobe Photoshop",
        logo: "/icons/photoshop.svg",
        text: "Photo editing, social media graphics, ad creatives, retouching, and polished marketing visuals.",
      },
      {
        name: "Adobe Illustrator",
        logo: "/icons/illustrator.svg",
        text: "Vector logos, icons, illustrations, brand marks, print layouts, and scalable design assets.",
      },
    ],
    process: [
      { title: "Discovery", text: "Understand your business, audience, offer, brand style, and where each design will be used." },
      { title: "Direction", text: "Set visual direction with colors, layout style, references, and campaign or brand requirements." },
      { title: "Design", text: "Create polished graphics with strong hierarchy, readable text, and platform-ready sizing." },
      { title: "Deliver", text: "Hand over export-ready files for web, social, ads, or print, plus source files when included." },
    ],
    faq: [
      { q: "Do you provide graphic design services in Bangladesh?", a: "Yes. I provide graphic design services for businesses in Dhaka and across Bangladesh, with remote workflow available." },
      { q: "What graphic design work can you create?", a: "I can design logos, brand identity assets, social media posts, ad creatives, flyers, brochures, banners, and marketing graphics." },
      { q: "Can you design social media and ad creatives?", a: "Yes. I create static posts, carousel designs, campaign graphics, and Meta Ads creatives with clear messaging and brand consistency." },
      { q: "Will I receive editable design files?", a: "You receive export-ready files, and editable source files can be included depending on the project scope." },
    ],
  },
  "ui-design": {
    service: "ui-design",
    imageSettingKey: "ui_design_image",
    eyebrow: "UI/UX Design Services",
    title: <>UI/UX Design Services <span className="text-primary">Bangladesh.</span></>,
    schemaTitle: "UI/UX Design Services Bangladesh",
    description: "UI/UX design services in Bangladesh for clean interfaces and conversion-focused user journeys on websites, landing pages, dashboards, and digital products.",
    icon: "layers",
    heroImage: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1200&q=80",
    overviewTitle: "Interfaces That Feel Clear And Useful",
    overview: "Good UI removes friction. I focus on hierarchy, responsiveness, accessibility, and user paths that help people take action.",
    portfolioTitle: "Featured UI/UX Work",
    features: [
      { icon: "schema", title: "Wireframes", text: "Structure pages and flows before visual polish to avoid wasted build time." },
      { icon: "web_asset", title: "High-Fidelity UI", text: "Responsive screens with clear hierarchy, spacing, and brand fit." },
      { icon: "touch_app", title: "Conversion UX", text: "User journeys and CTAs designed around real business outcomes." },
    ],
    tools: [
      {
        name: "Figma",
        logo: "https://cdn.simpleicons.org/figma/C6A75E",
        text: "Interface design, prototypes, responsive layouts, and developer handoff.",
      },
    ],
    process: [
      { title: "Research", text: "Clarify users, goals, competitors, and conversion actions." },
      { title: "Structure", text: "Map screens, sections, and user paths." },
      { title: "Design", text: "Create polished responsive interface layouts." },
      { title: "Handoff", text: "Prepare assets and notes for development." },
    ],
    faq: [
      { q: "Do you design mobile screens?", a: "Yes. Responsive layout is included in the design process." },
      { q: "Can you redesign an existing page?", a: "Yes. I can improve layout, hierarchy, CTA placement, and visual polish." },
      { q: "Do you provide developer handoff?", a: "Yes. Designs can include layout specs, assets, and implementation notes." },
    ],
  },
  "ads-expert-bangladesh": {
    service: "meta-ads",
    imageSettingKey: "meta_ads_image",
    ignoreCmsTitle: true,
    ignoreCmsContent: true,
    eyebrow: "Ads Expert Bangladesh",
    title: <>Ads Expert <span className="text-primary">Bangladesh.</span></>,
    schemaTitle: "Ads Expert Bangladesh",
    description: "Ads expert in Bangladesh for Meta Ads, Google Ads, TikTok Ads, creative testing, campaign structure, retargeting, and performance optimization.",
    icon: "ads_click",
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
    overviewTitle: "Paid Campaigns Built For Measurable Growth",
    overview: "Running ads is not only boosting posts. I plan paid campaigns for businesses in Dhaka and across Bangladesh with the right offer, audience, creative, funnel stage, tracking, and optimization rhythm.",
    portfolioTitle: "Advertising Proof & Results",
    features: [
      { icon: "track_changes", title: "Campaign Strategy", text: "Campaign structure aligned with offer, platform, funnel stage, target audience, budget, and conversion goal." },
      { icon: "science", title: "Creative Testing", text: "Test hooks, visuals, copy angles, placements, and audience segments to find winning creatives faster." },
      { icon: "monitoring", title: "Performance Optimization", text: "Monitor CPC, CTR, CPA, conversions, ROAS, frequency, and scaling opportunities across active campaigns." },
    ],
    toolsTitle: "Ad Platforms I Work With",
    toolsDescription: "Core ad platforms used to reach customers, test creatives, retarget visitors, and scale campaigns.",
    tools: [
      {
        name: "Meta Ads",
        logo: "https://cdn.simpleicons.org/meta/C6A75E",
        text: "Facebook and Instagram campaigns for awareness, leads, sales, retargeting, and offer testing.",
      },
      {
        name: "Google Ads",
        logo: "https://cdn.simpleicons.org/googleads/C6A75E",
        text: "Search and performance campaigns built around high-intent demand and measurable conversions.",
      },
      {
        name: "TikTok Ads",
        logo: "https://cdn.simpleicons.org/tiktok/C6A75E",
        text: "Short-form creative testing and audience campaigns for TikTok-native growth and remarketing.",
      },
    ],
    process: [
      { title: "Audit", text: "Review offer, account setup, tracking, audience, funnel, landing pages, and creative assets." },
      { title: "Plan", text: "Build campaign structure, budget plan, audience strategy, creative angles, and testing roadmap." },
      { title: "Launch", text: "Publish campaigns with conversion goals, tracking checks, budget controls, and clear test priorities." },
      { title: "Optimize", text: "Improve results using live campaign data, creative performance, audience signals, and funnel behavior." },
    ],
    faq: [
      { q: "Do you work as an ads expert in Bangladesh?", a: "Yes. I manage paid ad campaigns for businesses in Dhaka and across Bangladesh, with remote workflow available." },
      { q: "Which ad platforms do you manage?", a: "I work with Meta Ads, Google Ads, and TikTok Ads depending on your offer, audience, budget, and business goal." },
      { q: "Do you create ad creatives?", a: "Yes. Creative direction and static ad assets can be included so campaigns have stronger hooks, visuals, and messaging." },
      { q: "How soon can ad results improve?", a: "It depends on budget, offer, tracking, and data quality, but testing normally starts producing useful learnings within the first weeks." },
    ],
  },
  "wordpress-web-design-bangladesh": {
    service: "wordpress-dev",
    imageSettingKey: "wordpress_dev_image",
    ignoreCmsTitle: true,
    ignoreCmsContent: true,
    eyebrow: "WordPress Web Design",
    title: <>WordPress Web Design <span className="text-primary">Bangladesh.</span></>,
    schemaTitle: "WordPress Web Design Bangladesh",
    description: "WordPress web design in Bangladesh for editable business websites, blogs, landing pages, and WooCommerce stores.",
    parentService: { href: "/web-design-services-bangladesh", label: "Part of my web design services" },
    icon: "language",
    heroImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&q=80",
    overviewTitle: "Editable WordPress Websites Built For Business",
    overview: "I build WordPress websites that balance clean design, speed, SEO structure, and easy content editing for businesses in Dhaka and across Bangladesh.",
    portfolioTitle: "Featured WordPress Web Design Projects",
    features: [
      { icon: "edit", title: "Editable Website Pages", text: "Service pages, landing pages, blog layouts, and core business content you can update without code." },
      { icon: "storefront", title: "WooCommerce Setup", text: "Product pages, categories, and store structure for small e-commerce workflows inside WordPress." },
      { icon: "speed", title: "Speed & SEO Structure", text: "Clean page hierarchy, optimized assets, metadata basics, and mobile-friendly layouts from launch." },
    ],
    tools: [
      {
        name: "WordPress",
        logo: "https://cdn.simpleicons.org/wordpress/C6A75E",
        text: "Flexible CMS for business websites, blogs, service pages, landing pages, and WooCommerce stores.",
      },
      {
        name: "WooCommerce",
        logo: "https://cdn.simpleicons.org/woocommerce/C6A75E",
        text: "WordPress e-commerce setup for products, checkout, categories, and store management.",
      },
    ],
    process: [
      { title: "Scope", text: "Define pages, features, content, editing needs, and any WooCommerce requirements." },
      { title: "Build", text: "Create responsive WordPress pages with practical editing controls." },
      { title: "Optimize", text: "Improve speed, mobile layout, SEO fundamentals, and content structure." },
      { title: "Handoff", text: "Launch the site and show how to update text, images, pages, and posts." },
    ],
    faq: [
      { q: "Do you provide WordPress web design in Bangladesh?", a: "Yes. I build WordPress websites for businesses in Dhaka and across Bangladesh, with remote workflow available." },
      { q: "Can I edit my WordPress website myself?", a: "Yes. Pages, text, images, blog posts, and key sections are set up so you can update them without code." },
      { q: "Do you build WooCommerce stores?", a: "Yes. WooCommerce is available for product pages, categories, cart, checkout, and basic store structure." },
      { q: "Can you redesign an existing WordPress website?", a: "Yes. I can redesign, restructure, or optimize an existing WordPress site for speed, mobile, and SEO basics." },
    ],
  },
  "shopify-website-design-bangladesh": {
    service: "shopify-website-design-bangladesh",
    eyebrow: "Shopify Website Design",
    title: <>Shopify Website Design <span className="text-primary">Bangladesh.</span></>,
    schemaTitle: "Shopify Website Design Bangladesh",
    description: "Shopify website design in Bangladesh for product stores, checkout flow, inventory structure, and campaign-ready storefronts.",
    parentService: { href: "/web-design-services-bangladesh", label: "Part of my web design services" },
    icon: "shopping_cart",
    heroImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80",
    overviewTitle: "E-commerce Stores Built Around Buying Flow",
    overview: "Shopify fits product businesses that need clean product pages, inventory structure, checkout flow, and campaign-ready storefronts.",
    portfolioTitle: "Featured Shopify Projects",
    features: [
      { icon: "inventory_2", title: "Product Structure", text: "Collections, product pages, variants, and key store content arranged clearly." },
      { icon: "shopping_bag", title: "Checkout Flow", text: "Storefront layout focused on product discovery, cart confidence, and checkout readiness." },
      { icon: "campaign", title: "Campaign Pages", text: "Landing pages and promo sections ready for ads, launches, and seasonal offers." },
    ],
    tools: [
      {
        name: "Shopify",
        logo: "https://cdn.simpleicons.org/shopify/C6A75E",
        text: "E-commerce platform for products, checkout, inventory, and store management.",
      },
    ],
    process: [
      { title: "Scope", text: "Define products, collections, payment needs, shipping flow, and content." },
      { title: "Build", text: "Create responsive storefront pages and core e-commerce structure." },
      { title: "Optimize", text: "Tighten product presentation, speed basics, and SEO fundamentals." },
      { title: "Handoff", text: "Show how to update products, pages, collections, and campaigns." },
    ],
    faq: [
      { q: "Do you build Shopify sites?", a: "Yes. Shopify is the best fit when you sell physical products and need a dedicated checkout and inventory system." },
      { q: "Can I edit products myself?", a: "Yes. Product names, prices, descriptions, collections, and images can be managed from Shopify." },
      { q: "Can you improve an existing Shopify store?", a: "Yes. I can improve storefront structure, product pages, campaign pages, and speed basics." },
    ],
  },
  seo: {
    service: "seo",
    imageSettingKey: "seo_image",
    eyebrow: "SEO Service Bangladesh",
    title: <>SEO <span className="text-primary">Service Bangladesh.</span></>,
    schemaTitle: "SEO Service Bangladesh",
    description: "SEO service in Bangladesh for technical fixes, on-page optimization, and content structure that help search engines understand and trust your website.",
    icon: "query_stats",
    heroImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    overviewTitle: "SEO Foundations For Sustainable Traffic",
    overview: "Search performance starts with clean structure, indexable pages, useful content, and strong internal signals.",
    portfolioTitle: "SEO Related Projects",
    features: [
      { icon: "travel_explore", title: "Technical SEO", text: "Indexability, crawlability, metadata, speed basics, and structured content checks." },
      { icon: "article", title: "On-Page SEO", text: "Titles, headings, copy structure, internal links, and intent matching." },
      { icon: "analytics", title: "SEO Planning", text: "Practical content and page recommendations tied to business goals." },
    ],
    process: [
      { title: "Audit", text: "Review pages, technical blockers, metadata, and search intent fit." },
      { title: "Prioritize", text: "Rank fixes by likely impact and implementation effort." },
      { title: "Optimize", text: "Improve page structure, content, and technical basics." },
      { title: "Monitor", text: "Track changes and identify next opportunities." },
    ],
    faq: [
      { q: "Do you guarantee rankings?", a: "No one can honestly guarantee rankings, but the work improves search readiness and user relevance." },
      { q: "Can you optimize service pages?", a: "Yes. Service page structure, metadata, and internal links are core SEO work." },
      { q: "Do you provide audits?", a: "Yes. Audits can identify crawl, content, performance, and page-level issues." },
    ],
  },
};
