export const servicePageConfigs = {
  "graphic-design": {
    service: "graphic-design",
    imageSettingKey: "graphic_design_image",
    eyebrow: "Professional Design Solutions",
    title: <>Graphic Design <span className="text-primary">Services.</span></>,
    description: "Visual identity, marketing collateral, and digital assets designed to make your brand look sharper and sell with clarity.",
    icon: "brush",
    heroImage: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=1200&q=80",
    overviewTitle: "Visual Storytelling & Brand Consistency",
    overview: "Design work should not only look good. It should communicate clearly, stay consistent across channels, and support business goals.",
    portfolioTitle: "Featured Design Work",
    features: [
      { icon: "draw", title: "Logo & Identity", text: "Memorable identity systems with reusable marks, colors, typography, and brand direction." },
      { icon: "campaign", title: "Marketing Collateral", text: "Flyers, brochures, social posts, and sales assets built for campaign consistency." },
      { icon: "palette", title: "Creative Direction", text: "A clear visual system that keeps every brand touchpoint aligned." },
    ],
    toolsTitle: "Apps That I Use",
    toolsDescription: "Core design apps used to create polished graphics, brand assets, and marketing visuals.",
    tools: [
      {
        name: "Adobe Photoshop",
        logo: "/icons/photoshop.svg",
        text: "Photo editing, social media graphics, ad creatives, and polished marketing visuals.",
      },
      {
        name: "Adobe Illustrator",
        logo: "/icons/illustrator.svg",
        text: "Vector logos, icons, illustrations, brand marks, and scalable design assets.",
      },
    ],
    process: [
      { title: "Discovery", text: "Understand audience, goals, offers, and visual references." },
      { title: "Concept", text: "Explore creative directions and define the core visual language." },
      { title: "Refine", text: "Tighten chosen design route based on practical feedback." },
      { title: "Deliver", text: "Hand over organized files ready for web, social, or print." },
    ],
    faq: [
      { q: "What design files will I receive?", a: "You receive export-ready assets plus source files when included in the project scope." },
      { q: "Can you design for social ads?", a: "Yes. Static ad creatives, carousel assets, and campaign visuals are part of the design workflow." },
      { q: "Do you follow existing brand guidelines?", a: "Yes. I can work inside an existing system or build a new one from scratch." },
    ],
  },
  "ui-design": {
    service: "ui-design",
    imageSettingKey: "ui_design_image",
    eyebrow: "User Experience Design",
    title: <>UI/UX Design <span className="text-primary">Services.</span></>,
    description: "Clean interfaces and conversion-focused user journeys for websites, landing pages, dashboards, and digital products.",
    icon: "layers",
    heroImage: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1200&q=80",
    overviewTitle: "Interfaces That Feel Clear And Useful",
    overview: "Good UI removes friction. I focus on hierarchy, responsiveness, accessibility, and user paths that help people take action.",
    portfolioTitle: "Featured UI/UX Work",
    features: [
      { icon: "schema", title: "Wireframes", text: "Structure pages and flows before visual polish to avoid wasted build time." },
      { icon: "web_asset", title: "High-Fidelity UI", text: "Responsive screens with clear hierarchy, spacing, and brand fit." },
      { icon: "touch_app", title: "Conversion UX", text: "User journeys and CTAs designed around real business outcomes." },
    ],
    tools: [
      {
        name: "Figma",
        logo: "https://cdn.simpleicons.org/figma/C6A75E",
        text: "Interface design, prototypes, responsive layouts, and developer handoff.",
      },
    ],
    process: [
      { title: "Research", text: "Clarify users, goals, competitors, and conversion actions." },
      { title: "Structure", text: "Map screens, sections, and user paths." },
      { title: "Design", text: "Create polished responsive interface layouts." },
      { title: "Handoff", text: "Prepare assets and notes for development." },
    ],
    faq: [
      { q: "Do you design mobile screens?", a: "Yes. Responsive layout is included in the design process." },
      { q: "Can you redesign an existing page?", a: "Yes. I can improve layout, hierarchy, CTA placement, and visual polish." },
      { q: "Do you provide developer handoff?", a: "Yes. Designs can include layout specs, assets, and implementation notes." },
    ],
  },
  "meta-ads": {
    service: "meta-ads",
    imageSettingKey: "meta_ads_image",
    eyebrow: "Ads Expert",
    title: <>Ads <span className="text-primary">Expert.</span></>,
    description: "Paid advertising strategy and campaign management across Meta, Google Ads, and TikTok Ads to help brands reach the right audience and improve return on ad spend.",
    icon: "ads_click",
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
    overviewTitle: "Multi-Channel Ad Campaigns Built For ROI",
    overview: "Winning ads need the right offer, platform, creative, audience, tracking, and optimization. I plan and manage campaigns across major ad networks with clear testing and performance goals.",
    portfolioTitle: "Advertising Proof & Results",
    features: [
      { icon: "track_changes", title: "Campaign Strategy", text: "Campaign structure aligned with platform, offer, funnel stage, audience, and budget." },
      { icon: "science", title: "Creative Testing", text: "Test hooks, formats, angles, placements, and audiences to find winners faster." },
      { icon: "monitoring", title: "Performance Optimization", text: "Track CPC, CTR, conversions, ROAS, frequency, and scaling opportunities across ad networks." },
    ],
    toolsTitle: "Ad Networks I Use",
    toolsDescription: "Core advertising platforms used to reach customers, test creatives, and scale campaigns.",
    tools: [
      {
        name: "Meta Ads",
        logo: "https://cdn.simpleicons.org/meta/C6A75E",
        text: "Facebook and Instagram campaigns for awareness, leads, sales, and retargeting.",
      },
      {
        name: "Google Ads",
        logo: "https://cdn.simpleicons.org/googleads/C6A75E",
        text: "Search and performance campaigns built around high-intent demand and measurable conversions.",
      },
      {
        name: "TikTok Ads",
        logo: "https://cdn.simpleicons.org/tiktok/C6A75E",
        text: "Short-form creative testing and audience campaigns for TikTok-native growth.",
      },
    ],
    process: [
      { title: "Audit", text: "Review offer, account setup, tracking, funnel, creatives, and platform fit." },
      { title: "Plan", text: "Build campaign structure, budget plan, audience strategy, and testing roadmap." },
      { title: "Launch", text: "Publish campaigns with tracking, conversion goals, and budget controls." },
      { title: "Optimize", text: "Improve performance using data from active campaigns across each ad network." },
    ],
    faq: [
      { q: "Which ad platforms do you manage?", a: "I work with Meta Ads, Google Ads, and TikTok Ads depending on your goals, audience, and offer." },
      { q: "Do you create ad creatives?", a: "Yes. Creative direction and static assets can be included with campaign management." },
      { q: "How soon can results improve?", a: "It depends on budget, offer, platform, and data quality, but testing normally starts producing learnings within the first weeks." },
    ],
  },
  "wordpress-dev": {
    service: "wordpress-dev",
    imageSettingKey: "wordpress_dev_image",
    eyebrow: "Website Design",
    title: <>Web <span className="text-primary">Design.</span></>,
    description: "Fast, editable websites for service businesses, portfolios, landing pages, and e-commerce workflows.",
    icon: "terminal",
    heroImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&q=80",
    overviewTitle: "Websites You Can Actually Manage",
    overview: "I build practical websites that balance design, speed, SEO structure, and easy editing for everyday business use.",
    portfolioTitle: "Featured Web Design Projects",
    features: [
      { icon: "language", title: "Business Websites", text: "Service pages, landing pages, portfolio sections, and contact flows." },
      { icon: "shopping_cart", title: "E-commerce Setup", text: "Shopify or WordPress storefront structure for products and campaigns." },
      { icon: "speed", title: "Speed & SEO Basics", text: "Clean structure, optimized assets, and technical fundamentals." },
    ],
    tools: [
      {
        name: "WordPress",
        logo: "https://cdn.simpleicons.org/wordpress/C6A75E",
        text: "Editable business websites, landing pages, and content-managed sections.",
      },
      {
        name: "Shopify",
        logo: "https://cdn.simpleicons.org/shopify/C6A75E",
        text: "Clean storefront layouts, product pages, and conversion-ready e-commerce flows.",
      },
    ],
    process: [
      { title: "Scope", text: "Define pages, functionality, assets, and content needs." },
      { title: "Build", text: "Develop responsive pages and editable website sections." },
      { title: "Optimize", text: "Improve speed, SEO basics, and mobile experience." },
      { title: "Launch", text: "Publish, test, and hand over management guidance." },
    ],
    faq: [
      { q: "Can I edit the site myself?", a: "Yes. Web design builds are structured so key content can be managed without code." },
      { q: "Do you build Shopify sites?", a: "Yes. Shopify and WordPress web design builds can both be handled depending on the business model." },
      { q: "Can you improve an existing site?", a: "Yes. I can redesign, optimize, or rebuild existing pages." },
    ],
  },
  seo: {
    service: "seo",
    imageSettingKey: "seo_image",
    eyebrow: "Search Visibility",
    title: <>SEO <span className="text-primary">Service.</span></>,
    description: "Technical fixes, page optimization, and content structure that help search engines understand and trust your website.",
    icon: "query_stats",
    heroImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    overviewTitle: "SEO Foundations For Sustainable Traffic",
    overview: "Search performance starts with clean structure, indexable pages, useful content, and strong internal signals.",
    portfolioTitle: "SEO Related Projects",
    features: [
      { icon: "travel_explore", title: "Technical SEO", text: "Indexability, crawlability, metadata, speed basics, and structured content checks." },
      { icon: "article", title: "On-Page SEO", text: "Titles, headings, copy structure, internal links, and intent matching." },
      { icon: "analytics", title: "SEO Planning", text: "Practical content and page recommendations tied to business goals." },
    ],
    process: [
      { title: "Audit", text: "Review pages, technical blockers, metadata, and search intent fit." },
      { title: "Prioritize", text: "Rank fixes by likely impact and implementation effort." },
      { title: "Optimize", text: "Improve page structure, content, and technical basics." },
      { title: "Monitor", text: "Track changes and identify next opportunities." },
    ],
    faq: [
      { q: "Do you guarantee rankings?", a: "No one can honestly guarantee rankings, but the work improves search readiness and user relevance." },
      { q: "Can you optimize service pages?", a: "Yes. Service page structure, metadata, and internal links are core SEO work." },
      { q: "Do you provide audits?", a: "Yes. Audits can identify crawl, content, performance, and page-level issues." },
    ],
  },
};
